daily_backup_hours:
- '00'
- '12'
- '16'
- '20'
directories:
  cities_skylines: C:\Users\xicu\AppData\Local\Colossal Order\Cities_Skylines
  documents: C:\Users\xicu\Documents
  minecraft: C:\Users\xicu\AppData\Roaming\.minecraft
last_backup:
  daily: 6
  monthly: November
  weekly: 45
  yearly: 2024
last_execution:
  failing_point: None
  success: true
remotes:
  onedrive: onedrive:/
  raspi: raspi:~/backups
